import Head from "next/head";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  RedirectToSignIn,
  RedirectToUserProfile,
} from "@clerk/clerk-react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignedIn>
          <RedirectToSignIn />
        </SignedIn>

        <SignedOut>
          <RedirectToSignIn />
        </SignedOut>
      </main>
    </>
  );
}
