import Head from "next/head";
import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  useUser,
  RedirectToSignIn,
  RedirectToUserProfile,
} from "@clerk/clerk-react";
import { useRouter } from 'next/router';
import { useEffect, useState } from "react";


export default function Home({ Component, pageProps }) {
  const router = useRouter();
  const { user, isSignedIn } = useUser();

  useEffect(() => {
    if(isSignedIn){
      router.push("/todos");
    }
    
  }, [isSignedIn]);

  return (
    <>
      <Head>
        <title>Homework</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignedOut>
          <RedirectToSignIn redirectUrl="/todos"/>
        </SignedOut>
      </main>
    </>
  );
}
