import Head from "next/head";
import { Inter } from "next/font/google";
import { SignedIn, SignIn } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import styles from "../styles/to-do.module.css";
import NavBar from "../templates/navbar";
import AddModal from "../templates/addmodal";
import EditModal from "../templates/editmodal";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Todos({ Component, pageProps }) {
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [uniqueCategories, setUniqueCategories] = useState([]);
  const [onHomePage, setOnHomePage] = useState(true);

  async function removeTask(taskId) {
    const response = await fetch(
      process.env.NEXT_PUBLIC_DB_API_ENDPOINT + "/toDo/" + taskId,
      {
        method: "DELETE",
        headers: { "x-apikey": process.env.NEXT_PUBLIC_DB_API_KEY },
      }
    ).then((res) => res);
    getTasks();
  }

  async function filterCategories(category) {
    const response = await fetch(
      process.env.NEXT_PUBLIC_DB_API_ENDPOINT + "/toDo/category/" + category,
      {
        method: "GET",
        headers: { "x-apikey": process.env.NEXT_PUBLIC_DB_API_KEY },
      }
    );
    const data = await response.json();
    // update state -- configured earlier.
    setTasks(data);
  }

  async function completeTask(task) {
    const response = await fetch(
      process.env.NEXT_PUBLIC_DB_API_ENDPOINT + "/toDo/" + task._id,
      {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          "x-apikey": process.env.NEXT_PUBLIC_DB_API_KEY,
        },
        body: JSON.stringify({
          _id: task._id,
          ownerId: task.ownerId,
          title: task.title,
          description: task.description,
          category: task.category,
          completed: !task.completed,
        }),
      }
    );
  }

  const getTasks = async () => {
    const response = await fetch(
      process.env.NEXT_PUBLIC_DB_API_ENDPOINT + "/toDo",
      {
        method: "GET",
        headers: { "x-apikey": process.env.NEXT_PUBLIC_DB_API_KEY },
      }
    );
    const data = await response.json();
    // update state -- configured earlier.
    setTasks(data);
    setLoading(false);
  };

  function getUniqueCategories(arr) {
    let newArr = [];
    arr.forEach((item) => {
      newArr.push(item.category);
    });
    const setData = new Set(newArr);
    console.log(Array.from(setData));
    setUniqueCategories(Array.from(setData));
  }

  useEffect(() => {
    getTasks();
  }, []);

  useEffect(() => {
    getUniqueCategories(tasks);
  }, [loading, uniqueCategories.length]);

  if (loading) {
    return <div>Loading...</div>;
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar></NavBar>
        <div className={`${styles.maxheight} container-fluid text-center`}>
          <div className={`${styles.maxheight} row`}>
            <div className={`${styles.leftmenu} col`}>
              <h1>Categories</h1>
              <h2 onClick={getTasks}>Reset</h2>
              {onHomePage ? (
                uniqueCategories.map((task, key) => {
                  return (
                    <>
                      <p onClick={() => filterCategories(task)}>{task}</p>
                    </>
                  );
                })
              ) : (
                <p>To see full list again, Go to home on the navbar</p>
              )}
            </div>
            <div className={`${styles.rightmenu} col-9`}>
              <h1>Tasks</h1>
              {/* This is a template */}
              {tasks.map((task) => {
                return (
                  <>
                    <div className="container">
                      <h2>{task.title}</h2>
                      <h3>Category: {task.category}</h3>
                      <p>{task.description}</p>
                      <input
                        type="checkbox"
                        id="completedCheckbox"
                        name="completed"
                        defaultChecked={task.completed}
                        onChange={(e) => completeTask(task)}
                      ></input>
                      <label htmlFor="completedCheckbox">
                        {" "}
                        Check to complete
                      </label>
                      <br></br>
                      <Link
                        href={{
                          pathname: `todos/[id]`,
                          query: {
                            id: task._id
                          }
                        }}
                      >
                        Edit
                      </Link>
                      <button
                        className={`btn btn-primary`}
                        type="button"
                        onClick={() => removeTask(task._id)}
                      >
                        Remove
                      </button>
                    </div>
                    <hr></hr>
                  </>
                );
              })}
            </div>
            <button
              className={`${styles.addToDo} btn btn-primary`}
              type="button"
              data-bs-toggle="modal"
              data-bs-target="#addModal"
            >
              +
            </button>
            <AddModal
              uniqueCategories={uniqueCategories}
              parentTasks={tasks}
              getTasks={getTasks}
            ></AddModal>
          </div>
        </div>
      </>
    );
  }
}
