import Head from "next/head";
import { Inter } from "next/font/google";
import { SignedIn, SignIn } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import styles from "../styles/to-do.module.css";
import NavBar from "./templates/navbar";
import AddModal from "./templates/addmodal";

export default function Todos({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>
      <div className={`${styles.maxheight} container-fluid text-center`}>
        <div className={`${styles.maxheight} row`}>
          <div className={`${styles.leftmenu} col`}>
            <h1>Categories</h1>
            {/* This is a template */}
            <ul>
              <li>Something</li>
            </ul>
          </div>
          <div className={`${styles.rightmenu} col-9`}>
            <h1>Tasks</h1>
            {/* This is a template */}
            <div className="container">
              <h2>Task 1</h2>
              <p>About something</p>
              <input
                type="checkbox"
                id="vehicle1"
                name="vehicle1"
                value="Bike"
              ></input>
              <label for="vehicle1"> Check to complete</label>
              <br></br>
              <button>Edit</button>
              <hr></hr>
            </div>
          </div>
          <button
            className={`${styles.addToDo} btn btn-primary`}
            type="button"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal"
          >
            +
          </button>
          <AddModal></AddModal>
        </div>
      </div>
    </>
  );
}
